name: Build and Test
on:
  push:
    branches: [ master ]
  pull_request:
    type: [ synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-cache-${{ hashFiles('./stack.yaml.lock') }}
    - uses: cachix/cachix-action@v8
      with:
        name: haskell
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Test
      run: nix-shell --run 'stack test'
    - name: upload cachix
      run: nix-store --query --references $(nix-instantiate shell.nix) | xargs nix-store --realise | xargs nix-store --query --requisites | cachix push haskell
    - name: Install
      run: nix-shell --run 'stack install'
    - uses: actions/upload-artifact@v2
      with:
        name: dhall-aws-cloudformation-linux
        path: ~/.local/bin/dhall-aws-cloudformation-exe
  # build-macOS:
  #   runs-on: macOS-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: cachix/install-nix-action@v12
  #     with:
  #       nix_path: nixpkgs=channel:nixos-20.09
  #   - name: Cache
  #     uses: actions/cache@v1
  #     with:
  #       path: ~/.stack
  #       key: ${{ runner.os }}-stack-cache-${{ hashFiles('./stack.yaml.lock') }}
  #   - uses: cachix/cachix-action@v8
  #     with:
  #       name: haskell
  #       authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #   - run: nix-shell --run 'stack install'
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: dhall-aws-cloudformation-macOS
  #       path: ~/.local/bin/dhall-aws-cloudformation-exe
  publish:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
        - test
        # - build-macOS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dhall-aws-cloudformation-linux
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: dhall-aws-cloudformation-macOS
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LAST_RELEASE=$(hub release -L 1)
          LOCAL_VERSION=$(dhall text < ./version.dhall)
          echo "main version is $LAST_RELEASE and current version is $LOCAL_VERSION"
          if [ $LAST_RELEASE != $LOCAL_VERSION ];then
            hub release create -m "${LOCAL_VERSION}" -a ./dhall-aws-cloudformation-linux "${LOCAL_VERSION}"
          fi
